apiVersion: v1beta1
id: mysql
kind: Pod
desiredState:
  manifest:
    version: v1beta1
    id: mysql
    containers:
      - name: mysql
        image: openshift/mysql-55-rhel7 
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: yourpassword
        ports:
          - containerPort: 3306
labels:
  name: mysql
