FROM cgoern/atomicapp-rhel7:0.0.1

MAINTAINER Christoph Görn <goern@redhat.com>

LABEL io.projectatomic.nulecule.specversion 0.0.1-alpha

LABEL Build docker build --rm --tag cgoern/mysql55-rhel7-atomicapp .


ADD /nulecule /Dockerfile README.asciidoc gpl-3.0.txt /application-entity/
ADD /artifacts /application-entity/artifacts
